version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/contracts/wine-black"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "cargo"
    groups:
      patch-updates:
        update-types:
          - "patch"
      minor-updates:
        update-types:
          - "minor"

  - package-ecosystem: "npm"
    directory: "/bot"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "npm"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
